### ISSUE TITLE
Cartographers freeze the game

### ISSUE THREAD

**Issue by JleHuBbluKoT** [finallion/The-Graveyard-FORGE-#1]
All cartographers who can trade me a map that leads to large graveyards cause serious freezes.  Cartographers who do not have this trade do not cause any issues, vanilla trades for woodland mansion maps and ocean maps work fine. I can't check if the graveyard map itself is working properly because freeze does not let the map to load.
![2021-10-13_23 03 35](https://user-images.githubusercontent.com/45314340/137204920-ddc08217-9b36-48c1-a978-e09a1d4a3775.png)

**Comment by finallion** [comment]
Fixed in version 1.1
