### ISSUE TITLE
[1.18.1] Suggestion - GeckoLib Dependency 

### ISSUE THREAD

**Issue by elder-sign** [finallion/The-Graveyard-FORGE-#10]
Would it be possible to list GeckoLib as a dependency in the way that the curse app understands that if it installs the graveyard mod it also needs to install gecko? Scanning through hundreds of lines of errors when rebuilding a pack through curse is not a lot of fun

**Comment by finallion** [comment]
I updated the dependency to be required. I don't know if that is enough for the app to understand, but not sure what else I can do.

**Comment by elder-sign** [comment]
Just did a new test profile on curselauncher and it looks like your fix worked, thank you
