### ISSUE TITLE
Mobs not spawning 3.0 (1.20.1 FORGE) 

### ISSUE THREAD

**Issue by jay213333** [finallion/The-Graveyard-FORGE-#100]
### What's the issue you encountered?

Lion (discord) asked that I open this ticket with log to possibly find out why graveyard mobs aren't spawning in overworld. 

[latest.log](https://github.com/finallion/The-Graveyard-FORGE/files/14201328/latest.log)

### How can the issue be reproduced?

Tried testing with new worlds. Same outcome. No graveyard mobs ):

**Comment by zeid0ne** [comment]
Same issue 
![image](https://github.com/finallion/The-Graveyard-FORGE/assets/38461940/5050e5e1-e9a5-4168-a6e4-e9482ace247e)

**Comment by jay213333** [comment]
Hey devs confirmed bug via discord and are patching it in the next couple days.

**Comment by finallion** [comment]
Fixed in 3.1

**Comment by AikaBack** [comment]
for how many version did they not spawn? I have this mod and also didnt notice skeletons and ghouls spawning at night but didnt give it a thought

**Comment by finallion** [comment]
On version 1.20.1 for Forge
