### ISSUE TITLE
How do i add compat with mca villagers and blood collection ?

### ISSUE THREAD

**Issue by zeid0ne** [finallion/The-Graveyard-FORGE-#102]
### Overview

How do i add compat with mca villagers and blood collection ?

Is a config available ?
It's your mod that need to do the change ?
It's mca that need to do the change ?

thanks !

**Comment by finallion** [comment]
There is a config file in which you can specify the mob type, from which you can collect blood. I dont know if the mca villagers are an own type or just regular villagers though.

**Comment by Luke100000** [comment]
Yes, own type, `mca:male_villager` and `mca:female_villager`
