### ISSUE TITLE
Why the mod adds another dimension?

### ISSUE THREAD

**Issue by JuanPacoPedrodelaMar** [finallion/The-Graveyard-FORGE-#103]
### Overview

Every time I load my server with the mod it says that there is a dimension which id is "graveyard:past". Is this dimension used on the mod? because i couldn´t find a review or post where it mentions that this mod has another dimension.

**Comment by finallion** [comment]
Its a WIP and the file got accidently added to the repository - I can't remove it or else it will break forge mods

**Comment by JuanPacoPedrodelaMar** [comment]
wdym by it will break forge mods?

**Comment by finallion** [comment]
There is a Forge bug, where removing a dimension breaks the world
