### ISSUE TITLE
[1.20.1] Ghoul and ghouling missing texture when uses /summon or spawns by spawner

### ISSUE THREAD

**Issue by BradClc** [finallion/The-Graveyard-FORGE-#104]
### What's the issue you encountered?

When I play integrated_stronghold with its graveyard datapack which add spawner of mobs(ghoul, nightmare,vindicator and acolyte) from graveyard. I found that ghouls spawn by spawner lose texture and its appear animation(rise from dirt). Then I use /summon to summon ghoul and ghouling, I found that they both lose texture and appear animation. But if I use spawn egg to summon, their textures and animation of spawn would be fine.

### How can the issue be reproduced?

Add mods mentioned above(integrated stronghold require create,quark and supplementaries), use /summon graveyard_ghoul. By the way I use Embeddium and oculus for using shader.

### Additional information

![2024-02-27_00 13 17](https://github.com/finallion/The-Graveyard-FORGE/assets/88281511/a5bc0e3f-5126-4fd2-9503-b030bed65e14)
![2024-02-27_00 06 11](https://github.com/finallion/The-Graveyard-FORGE/assets/88281511/a6d1d189-6173-406b-9525-8636ec9a737a)

**Comment by finallion** [comment]
Fixed in 3.3
