### ISSUE TITLE
[1.19.3] "Error: package software.bernie.geckolib3 does not exist" When building

### ISSUE THREAD

**Issue by Asomeones222** [finallion/The-Graveyard-FORGE-#105]
When attempting to execute ```"gradlew build"``` without making any changes to the project, I encounter this error:
```
"Error: package software.bernie.geckolib3 does not exist".
```

In IntelliJ IDEA I first run ```"gradlew genIntellijRuns"``` , followed by ```"gradlew build"```, the latter of which results in the error message ```"package software.bernie.geckolib3 does not exist"```. After checking the external libraries, it appears that all libraries are installed except for this one. I also experienced the same issue in VSCode after running ```"gradlew genVSCodeRuns"``` instead.

Interestingly, this problem did not occur with version 1.20, and I was able to build the project successfully.  I tried to clean and reinstall dependencies multiple times, but the issue still persisted. Does anyone have an idea what might be the problem?

Specs: Windows 10 Pro Version 10.0.19045 Build 19045
Java version: OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)

**Comment by finallion** [comment]
It seems to be an issue with the mod file. Removing this entry should solve the issue.

src/main/resources/META-INF/mods.toml

[[dependencies.graveyard]]
    modId="geckolib3"
    mandatory=true
    versionRange="[4.0.6,)"
    ordering="NONE"
    side="BOTH"
