### ISSUE TITLE
Texture 1.20.1 Forge

### ISSUE THREAD

**Issue by Krimatoria** [finallion/The-Graveyard-FORGE-#106]
### What's the issue you encountered?

![image](https://github.com/finallion/The-Graveyard-FORGE/assets/106809386/6189594f-0309-4516-9e02-1651d32a2428)

### How can the issue be reproduced?

The_Graveyard_3.1_(FORGE)_for_1.20.1.jar

**Comment by finallion** [comment]
Fixed in version 3.3
