### ISSUE TITLE
[1.20.4 NeoForge] server not starting

### ISSUE THREAD

**Issue by MSandro** [finallion/The-Graveyard-FORGE-#108]
### What's the issue you encountered?

I can't launch a server with this mod.

### How can the issue be reproduced?

the server should load up with the mod.

### Logs

https://gist.github.com/MSandro/0fa7695dc221d9375eec1abfc1beae43

### Additional information

NeoForge Version: 20.4.211
The_Graveyard_3.2_(NEOFORGE)_for_1.20.4.jar

**Comment by EfficientStinkbug** [comment]
Same for me! I need to put my server update on hold for now, otherwise all the graveyard stuff would be gone...
Client works fine.

**Comment by finallion** [comment]
Fixed in version 3.3
