### ISSUE TITLE
Server Crash "Feature placement"

### ISSUE THREAD

**Issue by Kqmu** [finallion/The-Graveyard-FORGE-#112]
so the Issue I am encountering is a server "feature placement Crash" and scratching my head trying to debug the issue and was wondering if I could get some help, fromt he crash report it seems to be related to graveyard:crypt but when I disable that from generating it jumps to another structure from another mod, hopefully this crashlog from the server proves helpful to you 

[crash-2024-04-17_07.17.12-server.txt](https://github.com/finallion/The-Graveyard-FORGE/files/15007460/crash-2024-04-17_07.17.12-server.txt)

Line 69; is what brings me to this specfic github place
![image_2024-04-17_032951200](https://github.com/finallion/The-Graveyard-FORGE/assets/70139586/e9376ad6-6eae-4351-aac0-bd5f72eebe3d)

**Comment by Reshy** [comment]
https://pastebin.com/FFhRnRmK

Same or similar issue, seems related to waterlogging of Wither Skulls.

**Comment by Kqmu** [comment]
Issue was solved turned out to be an issue with Amendments' recent update (they released a hotfix fixing the issue) @Reshy this issue might be fixed to you if you update Amendments <3 https://github.com/MehVahdJukaar/amendments/issues/63

**Comment by Kqmu** [comment]
Forgot to mention but this thread can be closed whenever thread admins sees it ! :)
