### ISSUE TITLE
graveyards does not generate in a BIOMES O PLENTY world

### ISSUE THREAD

**Issue by quakeman00** [finallion/The-Graveyard-FORGE-#12]
custom structures like waystones / quark / mo shiz / productive bees do generate in a biomesoplenty world gen but the graveyards does not

**Comment by itsdinkd** [comment]
its definitely generating in mine....

**Comment by finallion** [comment]
Hm they aren't generating in mine, too. I'm not sure if the mods you mentioned (waystones, quark etc.) really add structures? Aren't these features? These would behave differently. 
I'm not really sure what BOP is doing with TerraBlender and its still in beta, so maybe they'll fix this in the future.
Especially with 1.18.2 wanting to fix some off the overworld biome generation, I dont know if BOP will keep its own generator.
I'll have a look around.
