### ISSUE TITLE
4 Large Cemeteries back to back? [1.18.1]

### ISSUE THREAD

**Issue by itsdinkd** [finallion/The-Graveyard-FORGE-#13]
Is it normal for 4 Cemeteries to spawn right next to each other? Also is it normal for this many lootr chests to be there? there's about 200 chests. This is for 1.18.1 forge

(the yellow are chests)
![image](https://user-images.githubusercontent.com/35115304/147971748-cd03b55b-9580-4d7e-a2d8-c5dced991a7b.png)

![image](https://user-images.githubusercontent.com/35115304/147971733-570728fe-6ffd-4d91-ae18-4d261e6a819b.png)

**Comment by finallion** [comment]
This is one structure. Its jigsaw (like minecraft villages), so its generating with different parts. And yes, there are a lot of chests (coffins) - its a graveyard ;). There are also spawners to make it more difficulte to loot these chests.
And the loot can be quite nice, but most of the time it is bones and rotten flesh.

**Comment by itsdinkd** [comment]
yeah i wish i could say the loot is only bones and rotten flesh however that wasn't the case in this instance, no where near that. maybe its a fault of lootr, idk, it just sucks with zero control. 

Spawners were destroyed and I just have 100 chests chilling out for everyone to grab. blah.

**Comment by itsdinkd** [comment]
Just kidding, so actually no spawners are even spawning.

![image](https://user-images.githubusercontent.com/35115304/149600192-8b23b199-b2de-456e-b207-e1fd448633b5.png)

this is in single player.

**Comment by finallion** [comment]
It is day time?

**Comment by itsdinkd** [comment]
Yes. Do spawners get added only at night? because I've searched the entire area and there is no Minecraft:spawner
