### ISSUE TITLE
Abrupt fog effect upon entering graveyard biome

### ISSUE THREAD

**Issue by badasselectrician** [finallion/The-Graveyard-FORGE-#14]
I don't know if this is intentional or a problem with my game, but when i entered the graveyard biome "haunted_lakes" the fog effect just instantly appeared, with no smooth transition or anything. I wondered if it was a bug with other mods so i tested it with just the graveyard mod installed on a fresh world, and it was the exact same. It can be very annoying, especially when walking through the border between that biome and another one without the fog effect, as it'll create this awful flicker, the fog appearing and disappearing rapidly. You can see all of what i described in action in the video attached. I have not tested this in any other biome so i don't know if the same problem exists there. {EDIT} It does exist in other biomes.
 
Mod version: The_Graveyard_2.1_(FORGE)_for_1.16.4-1.16.5
Lib version: geckolib-forge-1.16.5-3.0.57
Forge version: 1.16.5 32.2.20
Using Curseforge profile.

https://user-images.githubusercontent.com/97315421/148610866-3c54e8c8-d8fe-4951-b754-b53ef983e521.mp4
#

**Comment by finallion** [comment]
This is not really a bug. If you enter the biome the fog renderer from minecraft kicks in. I know its abrupt, and I tried to make it smoother, but the fog engine is not really kind. But I'm going to look at it again when the biomes for 1.18 are released.

**Comment by badasselectrician** [comment]
> This is not really a bug. If you enter the biome the fog renderer from minecraft kicks in. I know its abrupt, and I tried to make it smoother, but the fog engine is not really kind. But I'm going to look at it again when the biomes for 1.18 are released.

Yeah after playing with the mod for a bit after making that video i did notice the renderer working a lot better. Guess it can't be helped when the game itself is unforgiving, and it's not like it's a major concern by any measure anyways lol. Thanks for looking into it though and good luck with developing the mod.

**Comment by finallion** [comment]
Should work a lot smoother in the newest version!
