### ISSUE TITLE
CurseForge desktop does not install GeckoLib

### ISSUE THREAD

**Issue by silentnyte** [finallion/The-Graveyard-FORGE-#15]
There may be a dependency missing telling CurseForge that GeckoLib is required.

**Comment by finallion** [comment]
Relates to https://github.com/finallion/The-Graveyard-FORGE-/issues/10

**Comment by finallion** [comment]
The depency of geckolib on curseforge is set to "required dependency". It shows in the Relations tab. Are you refering to the Curseforge app?

**Comment by silentnyte** [comment]
Yes, using the curseforge app the geckolib dependency is not installed for 1.16.5 Forge.

**Comment by finallion** [comment]
Sorry for the long wait, but it should work now!
