### ISSUE TITLE
[Feature Request]: Custom Loot Table Per Structure + Biome Whitelists

### ISSUE THREAD

**Issue by Tyrius1** [finallion/The-Graveyard-FORGE-#16]
Throughout each structure there are tons of loot chests with varying tables like bone_loot, flesh_loot, creeper_loot etc.. 
The goal would be to add 1 unique loot chest to each structure. 
For instance here where the yellow vase is. 
Below it is a 6 chests. 1 medium_loot, 1 small_loot and the rest are bone_loot.
What I would like to see is something like:  1 medium_loot, 1 small_loot, 3 bone_loot and 1 desert_gated_loot_1

The biggest reason I want to see this added personally is to make use of a different mod which allows for summoning bosses with custom AI at specified loot chests. If i were to designate graveyard:chests/medium_loot as the chest the boss were to spawn. It would not spawn at only this specified structure like desired.
![image](https://user-images.githubusercontent.com/29525146/149399878-a5182ec2-0f3d-4961-aa4b-c924de6f4330.png)

The 2nd feature I'd like to see added is a biome whitelist config entry for each structure. Making use of the "minecraft:desert" format preferably as this format gives much greater control of generation.

**Comment by finallion** [comment]
The white list is already done and I will upload it the next days. The custom loot chests is a pretty cool idea!

**Comment by MrBloodworth** [comment]
Another Vote From me. Looking forward to a Config file.

**Comment by finallion** [comment]
The biome whitelist is coming in the next update. I'll make an extra issue for the custom loot tables.

**Comment by Tyrius1** [comment]
Sweeeeet :) forgot to check back on this lol thanks!
