### ISSUE TITLE
No Mobs Spawns (The Graveyard 1.1 (FORGE) for 1.18.1)

### ISSUE THREAD

**Issue by MrBloodworth** [finallion/The-Graveyard-FORGE-#17]
I Am Not Seeing any Creatures from this mod in any spawns. 

Forge Version: 39.0.20
The Graveyard 1.1 (FORGE) for 1.18.1

**Comment by finallion** [comment]
They dont spawn naturally. Some spawn at night by graveyards.

**Comment by MrBloodworth** [comment]
Thats what I mean. I'm not seeing any by this mods structures.  They are empty.

What kind of concentration should I be seeing normally?

**Comment by finallion** [comment]
I checked and they are spawning but very rarely - to rare. The next update will change mob spawning generally, so that graveyard mobs will spawn like other mobs, so that should fix the issue. I will additionally increase mobs spawning weight for the structures.
