### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by zEpiixz** [finallion/The-Graveyard-FORGE-#2]
Im not exactly sure why if it has more to do with the world gen or with the merchant villager that tries to spawn.
But it seems like its realted to some kind of trade he gets from the graveyard mod.
If not im sorry.
https://pastebin.com/ttWaxJt3

**Comment by finallion** [comment]
Thanks for the report. I'll remove the map feature, as it is causing some issues in both versions of the mod.
