### ISSUE TITLE
Startup Crash 1.18.1 - Forge 39.0.45

### ISSUE THREAD

**Issue by HalestormXV** [finallion/The-Graveyard-FORGE-#20]
Mod Version The_Graveyard_1.2_(FORGE)_for_1.18.1.jar

Crashes on Startup with a mod failure to load error. Here is the log.
https://pastebin.com/apGBUHj7

**Comment by finallion** [comment]
I uploaded version 1.3 with some changes to the spawner logic. Let me know if this fixes the issue...!

**Comment by HalestormXV** [comment]
Looks like that update gave it a fix. It starts up now no issue.
