### ISSUE TITLE
Leftover `System.out.println` causing log spam (1.18)

### ISSUE THREAD

**Issue by Mrbysco** [finallion/The-Graveyard-FORGE-#21]
Hello, I believe you forgot to disable some `System.out.println`'s before you build your  `The Graveyard 1.3 (FORGE)` jar.

Currently you'll get a lot of `STOP` and `false` spam in your logs. Which can be traced to the `RevenantEntity` class.
[Code in question](https://github.com/finallion/The-Graveyard-FORGE-/blob/1.18/src/main/java/com/finallion/graveyard/entities/RevenantEntity.java#L103-L114)

There's also a println left in a [mixin](https://github.com/finallion/The-Graveyard-FORGE-/blob/1.18/src/main/java/com/finallion/graveyard/mixin/ClientPlayNetworkHandlerMixin.java#L46)

**Comment by finallion** [comment]
This is why you don't code in the middle of the night. Will release a version today fixing this mess.
