### ISSUE TITLE
Crash when I click on the "Create world" button

### ISSUE THREAD

**Issue by Finelarme9** [finallion/The-Graveyard-FORGE-#24]
Hey there. Thank you for this mod. Unfortunately I have a crash with the last version (1.5 Forge) when I click on the "Create world" button.  A compatibility problem with other mods I guess, because it works fine with just Terrablender/Geckolib. Let me know if you need my mods list. (No crash with the version 1.4 Forge)

=> https://pastebin.com/raw/tcQJtw1T

Thank you for your time.

**Comment by finallion** [comment]
The modlist would be great, because I can't reproduce the error!
It says in the log you posted: "Failure message: Mod graveyard requires geckolib3 3.0.0 or above. Currently, geckolib3 is not installed" Are you sure you have the correct dependencies installed?

**Comment by Finelarme9** [comment]
Hey there, sure :

The_Graveyard_1.5_(FORGE)_for_1.18.1.jar
geckolib-1.18-forge-3.0.10.jar = https://www.curseforge.com/minecraft/mc-mods/geckolib/files
TerraBlender-forge-1.18.1-1.1.0.73.jar = https://www.curseforge.com/minecraft/mc-mods/terrablender
ecosphericalexpansion-0.2.2.jar = https://www.curseforge.com/minecraft/mc-mods/ecospherical-expansion

Crash report = https://pastebin.com/raw/31hNu21V

The problem seems to be with The_Graveyard_1.5_(FORGE)_for_1.18.1.jar + ecosphericalexpansion-0.2.2.jar so. No more crash when I use the version The_Graveyard_1.5_(FORGE)_for_1.18.1_without_biomes.jar . I will open an issue for ecospherical-expansion mod.

**Comment by finallion** [comment]
The log you posted on the others mod side is a completly different one. That'd be helpful. That one says something about a wrong registration order of biome features.

Does it crash without ecospherical expansion?

**Comment by Finelarme9** [comment]
No crash without ecosphericalexpansion-0.2.2.jar. The fresh report is the last one below (https://pastebin.com/raw/31hNu21V), happening with 4 mods only.

**Comment by finallion** [comment]
Well it is either a compat issue or an issue on ecosphericals side. The error meesage doesn't suggest a compat issue rather a misplaced feature: in 1.18 the features added to biomes must be in a specific order. And all biomes added must have the same order, or else it throws a "IllegalStateException: Feature order cycle found". You can tell the dev to maybe check that again.

**Comment by Finelarme9** [comment]
Ok. I will tell that to ecosphericalexpansion-0.2.2.jar author. Thank you for your time!
