### ISSUE TITLE
Mobs Spawn Outside of Graveyards

### ISSUE THREAD

**Issue by MrBloodworth** [finallion/The-Graveyard-FORGE-#25]
In my current game, the mobs from this mod are appearing in normal, nightly mob/Monster spawns outside of the structures from this mod.

Not sure if this is intended. I assumed the creatures are unique to the graveyard structures.

Forge Version: 39.0.63
The_Graveyard_1.4_(FORGE)_for_1.18.1
[mod-list_2022-01-29_12.27.24.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/7964216/mod-list_2022-01-29_12.27.24.txt)

![Undead_Graveyard](https://user-images.githubusercontent.com/96947832/151670543-8e9fc415-b315-45c5-b5bd-aa73696db2b4.jpg)

**Comment by finallion** [comment]
It is intentional. They can be disabled in the config though.

**Comment by MrBloodworth** [comment]
I looked over the Config. No Way to constrain them to this mods placed structures?

Thanks for the replies.

**Comment by finallion** [comment]
If you disable them, you disable them from spawning naturally, not from spawning in structures. 
And by looking at the picture it looks like a horde spawn. That is still possible even when you disabled the natural spawning - so you would need to disable that in the config too!

**Comment by MrBloodworth** [comment]
I Don't Mind the horde. The ones just in the field like other monster spawns at night, that's what I was after!  Its nice I can disable them, I want them to be semi rare.

Prefect.
