### ISSUE TITLE
Skeleton creeper explodes in spectator mode

### ISSUE THREAD

**Issue by ifound1dollar** [finallion/The-Graveyard-FORGE-#29]
### What's the issue you encountered?

I was testing my modpack, looking for a custom ore in spectator mode when I encountered a skeleton creeper inside a cave. When I moved close to it, it detonated as if I was in survival or adventure mode.

### How can the issue be reproduced?

I was not able to reproduce the issue when summoning a skeleton creeper again in a cave.

**Comment by finallion** [comment]
This is not the case. As the skeleton creeper is just an extension of the normal creeper this would mean the vanilla creeper has this issue.
