### ISSUE TITLE
Nether lighting issue

### ISSUE THREAD

**Issue by Draxterio** [finallion/The-Graveyard-FORGE-#30]
### What's the issue you encountered?

Issue server side, lighting in the nether starts flickering constantly.

### How can the issue be reproduced?

Just opening the server and playtesting the nether.

### Additional information

There was no log indicating this flickering issue

**Comment by finallion** [comment]
Should be fixed in the next update. If it is causing you trouble you can set your render distance in the nether above 7, this should solve it temporarly

**Comment by finallion** [comment]
Fixed in version 1.6.
