### ISSUE TITLE
Biome Whitelists for Mob Spawning

### ISSUE THREAD

**Issue by ninyauwu** [finallion/The-Graveyard-FORGE-#31]
### Overview

It would be really helpful if we could set a specific biome whitelist for where the mods' monsters are allowed to spawn. Potentially there could be a boolean setting in the config that turns the biome blacklist into a whitelist or something like that.

### Why would this feature be useful?

Currently you have to blacklist everything except the biome you're trying to get them to spawn in, which when you have a biome mod or two such as biomes o plenty installed gets really annoying really fast.

**Comment by finallion** [comment]
Added in version 1.6.

**Comment by ninyauwu** [comment]
Great! Thank you :D
