### ISSUE TITLE
Minecraft 1.18.1 - Replace loot chests with custom coffins

### ISSUE THREAD

**Issue by DWX12** [finallion/The-Graveyard-FORGE-#32]
### Overview

Instead of double loot chests, create custom coffin models (a few different ones for variety) such as a partially broken one, a sort of European/fancy Dracula type coffin, and a sort of wooden crate typical of westerns. Could also indicate the value of the loot by how fancy or plain the coffin is.

### Why would this feature be useful?

There are already many wonderful models and textures, an improvement like this would help to tie the mod together more visually and aesthetically.

Time and time again I've seen mods use the old double chest for a coffin trick and with custom models for inventories/storage, that would visually put this mod above others. Plus, I'm sure many players out there would really enjoy having coffin chests for their dark or gothic builds especially with all the dark fantasy mods and mod packs out there.

Thanks so much for all the time and effort already put into creating this mod.

**Comment by finallion** [comment]
In version 1.8 for 1.18.2 implemented.
