### ISSUE TITLE
Crash with Voidscape

### ISSUE THREAD

**Issue by Darkfiend009** [finallion/The-Graveyard-FORGE-#35]
### What's the issue you encountered?

Crash when trying to go to the custom dimension added by the mod Voidscape. 1.18.2.

### How can the issue be reproduced?

1. Install both Voidscape and The Graveyard.
2. Hang out near Bedrock until your screen goes black.
3. Press z when prompted to go through the dialogue.
4. Begin loading the custom dimension.
5. Crash

### Logs

https://pastebin.com/PPkC8i2j

**Comment by finallion** [comment]
Found the issue. It will be fixed in the next version!
