### ISSUE TITLE
reproduce mod

### ISSUE THREAD

**Issue by shiyushui** [finallion/The-Graveyard-FORGE-#38]
### Overview

Hello author, can I reproduce your mod on the forum

**Comment by finallion** [comment]
Hey, sorry I don't understand what you want to do, could you ellaborate?

**Comment by shiyushui** [comment]
can I reprint your mod on the minecarft forum 
I will mark the author

**Comment by finallion** [comment]
What does reprint mean? Do you share the .jar file or do you copy the whole mod?

**Comment by shiyushui** [comment]
我可以转载你的mod到一个论坛上吗，我会标记作者的

**Comment by finallion** [comment]
Which forum?

**Comment by shiyushui** [comment]
https://www.mcutc.com

**Comment by finallion** [comment]
Yes, you can

**Comment by shiyushui** [comment]
thanks
