### ISSUE TITLE
[1.16.5] Suggestion (Biome Dictionary, ToolType)

### ISSUE THREAD

**Issue by drakray** [finallion/The-Graveyard-FORGE-#4]
I think your 3 new biomes should make use of the Forge Biome Tag
maybe something like:
 - graveyard:eroded_haunted_forest
   - SPOOKY
   - FOREST
   - DEAD/DRY
   - WASTELAND?
   - CONIFEROUS?
 - graveyard:haunted_forest
   - SPOOKY
   - FOREST
   - CONIFEROUS?
 - graveyard:haunted_lakes
   - SPOOKY
   - FOREST
   - WET/WATER?
   - CONIFEROUS?
   - MAGICAL?

For blocks, I think making mosstypeBlock should use toolType.HOE(?like hay bale), dirttypelock should use toolType.SHOVEL, and stonetypeBlock should use toolType.PICKAXE, as effective tools.

Urn/Vase could also have a slightly bigger inventory, since they can't be doubled(or maybe have a doubleChest version, vertical, a kind of memorial monolith?)

Thank you for your good work, it's an awesome mod :D

**Comment by finallion** [comment]
Thanks a ton for your improvements :). The new update should implement most of them! I increased the urn inventory size, otherwise they would be kind of useless or not used at all, but I like your idea of a doubled version!
