### ISSUE TITLE
Crypts that spawn in underwater lakes become flooded

### ISSUE THREAD

**Issue by Warhand** [finallion/The-Graveyard-FORGE-#40]
### What's the issue you encountered?

When a crypt spawns in an underground lake or other large body of water, a few different blocks don't spawn as air, and instead spawn as water, including a few different slabs, which become waterlogged.

This results in strange, disjointed patches of water spawning throughout the structure, ruining the atmosphere.

![2022-06-14_00 51 57](https://user-images.githubusercontent.com/29134223/173496572-6f46b753-7f43-419f-b32b-8e265d0d5807.png)
.

### How can the issue be reproduced?

Find a crypt that has generated in an underground lake or other large body of water.

### Logs

https://pastebin.com/UTGJAZui

### Additional information

I feel like the inclusion of the Structure gel API mod might rectify this issue, as it allows for mod authors to use a special type of block to fill structures, and when the structure spawns, it will replace those blocks with air, preventing any unwanted water, grass, or other worldgen features from replacing elements of the structure or spawning where they shouldn't be.

I feel as though that won't fix the waterlogged slabs issue tho, but I'm unsure how to really solve that specifically.

**Comment by finallion** [comment]
I added processors  in the newest versions to remove waterlogged blocks, it will still occur, but should be reduced quite a bit.
