### ISSUE TITLE
Graveyard grass block cannot have a path cut into it

### ISSUE THREAD

**Issue by archonsd** [finallion/The-Graveyard-FORGE-#42]
### What's the issue you encountered?

Ordinary Minecraft dirt blocks (including dirt with grass on it) can be made into paths with a shovel and a right mouse click.  Graveyard Grass block cannot.  Digging up the graveyard dirt gives you normal dirt which you can put back down and make a path out of, as a workaround.

### How can the issue be reproduced?

Put a shovel in your hand and right click any Graveyard grass block.

### Additional information

If this is intended, please let me know and I'll close the bug, or you can close it with comment..  It seems like this should just work and be an expected behavior, so I didn't put it in as a feature request.

Forge:  1.18.2-40.1.47
The Graveyard-Forge:  1.9

**Comment by finallion** [comment]
Fixed in 1.11
