### ISSUE TITLE
As soon as I click, create new world, it crashes

### ISSUE THREAD

**Issue by ghost** [finallion/The-Graveyard-FORGE-#43]
### What's the issue you encountered?

As soon as I click, create new world, it crashes

### How can the issue be reproduced?

As soon as I click, create new world, it crashes

### Additional information

[crash-2022-06-20_21.16.04-client.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/8940898/crash-2022-06-20_21.16.04-client.txt)

**Comment by finallion** [comment]
It seems like somewhere in the config, you set some structure values wrong (spacing has to be larger than separation). You can delete the config and restart the game.
