### ISSUE TITLE
Improve Simplified Chinese translation

### ISSUE THREAD

**Issue by VAN-192** [finallion/The-Graveyard-FORGE-#44]
### Overview

The simplified Chinese translation in the module has a lot of missing parts in the new version.

### Why would this feature be useful?

I have created a new Simplified Chinese translation that I hope can be used
[zh_cn.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/9046807/zh_cn.txt)
.

**Comment by finallion** [comment]
Thank you very much!
