### ISSUE TITLE
End graves are unreachable

### ISSUE THREAD

**Issue by brycen-gh** [finallion/The-Graveyard-FORGE-#48]
### What's the issue you encountered?

ender pearled to death

### How can the issue be reproduced?

throw pearl off the map

**Comment by finallion** [comment]
I‘m sorry I don’t understand what’s the issue. Which version are you on and why are graves spawning in the end? Ender pearls in the void don’t teleport you?

**Comment by brycen-gh** [comment]
Ah my bad, I had conflicting mods
