### ISSUE TITLE
Ghouls get stuck on Ferns

### ISSUE THREAD

**Issue by Reshy** [finallion/The-Graveyard-FORGE-#5]
![2021-11-27_22 56 06](https://user-images.githubusercontent.com/2096384/143732840-69c8f0fc-4724-4219-9d3e-586ad5102c21.png)
![2021-11-27_22 56 10](https://user-images.githubusercontent.com/2096384/143732777-6137f72b-9f8f-418c-a95a-98276edda69d.png)
![2021-11-27_22 56 21](https://user-images.githubusercontent.com/2096384/143732783-95dc5b88-21be-4e95-bf50-474f7e9acb36.png)

As you can see, they struggle to pathfinder up to hit me where I am, of the ones I spawned only one was able to, and even after hitting me once he got stuck.

**Comment by finallion** [comment]
The lower ones cant reach you because their hitbox is stuck inside the wall. I think it might be the same issue with the upper one, which got stuck inside a block when spawned.

**Comment by finallion** [comment]
I made a minor tweak so i shouldn't happen anymore. It seems to be some weird hitbox stuff going on and the ghoul thinking it can hit you.

**Comment by Reshy** [comment]
Thanks!  I'm not sure if they think I'm in range or not, as it only seems to happen with ferns specifically and not tall grass or just no grass blocks.

**Comment by Reshy** [comment]
Tested it, the recent update does fix the fern problem, thanks!
