### ISSUE TITLE
[1.18.2] Urns hold too much space!

### ISSUE THREAD

**Issue by MarioSMB** [finallion/The-Graveyard-FORGE-#50]
### Overview

The urns are relatively cheaply crafted (clay can be found almost anywhere) and they hold as much as a double chest while taking up only a single block of space, making them vastly superior to any other vanilla-based storage options.  
I think it would be a good idea to bring them back down to a single chest in space until they can be vertically stacked or something.

### Why would this feature be useful?

It would aid in balancing the mod's content a bit better.

**Comment by finallion** [comment]
There is an option in the config to scale down the inventory of the urns.

**Comment by MarioSMB** [comment]
![meme](https://user-images.githubusercontent.com/1998392/213209073-6f57f27b-b2f9-403b-9622-2267ebdcd3f3.jpg)

On a more serious note, the little urns and stuff should probably only have a single row of inventory space - this doesn't seem to be an option in the configuration currently.  
The default of a double chest worth of slots leaves a bit of a poor impression on an otherwise very high quality mod, I really do hope some consideration can be made to reduce their slots!
