### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by emilyskemily14** [finallion/The-Graveyard-FORGE-#51]
hiya, is there any reason why 1.19.2 wont work on the graveyard mod. I downloaded the mod and went to load a new world. whilst loading the world, it crashes. 1.19.2 wont work at all I've tried different  versions on forge on 1.19.2.

additionally to try and see if it was a problem with the graveyard mod on 1.19 I tried it on 1.19.1 and 1.19 and both of these had issues with just spawning in crypts. they appear to spawn in all the other graveyards on top of the surface but the crypts are none existent. 
any help please :)

**Comment by finallion** [comment]
Hey, without any logs there is nothing I can do.

**Comment by emilyskemily14** [comment]
> Hey, without any logs there is nothing I can do.

1.19.2 crash report
[crash-1.19.2.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/9484684/crash-1.19.2.txt)


no sure how to get logs for 1.19.1/1.19 as it doesnt crash, just doesnt spawn crypts

**Comment by finallion** [comment]
Go to your .minecraft/config folder and delete the graveyard config file. Then restart your game!

For the 1.19.1 issues you can look at the config. Maybe biomes are not whitelisted for the crypt. Does ./locate graveyard:crypt not find any?

**Comment by emilyskemily14** [comment]
appears to be working for 1.19.2 now thank you!
for 1.19.1 it wasn't finding any of the crypts but the others were presents

**Comment by ramon5457** [comment]
[crash-2022-09-04_13.34.48-server.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/9484835/crash-2022-09-04_13.34.48-server.txt)

Hi, I had this problem too which is fixed, but now everytime I join a world or server, it crashes and gives me this crash report. Any solution pls?

![image](https://user-images.githubusercontent.com/112813663/188317732-bcb171cf-e7af-4486-b497-63f2d73c4aa1.png)

**Comment by finallion** [comment]
This looks like something broke and structures aren't recognized/not there. You should reinstall the mod and delete the config.
