### ISSUE TITLE
Cant join servers

### ISSUE THREAD

**Issue by ramon5457** [finallion/The-Graveyard-FORGE-#52]
### What's the issue you encountered?

Hi, I am unable to join a server or singleplayer world. I am on 1.19.2 and everytime I join a singleplayer world it crashes with this report.
[crash-2022-09-04_13.34.48-server.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/9484846/crash-2022-09-04_13.34.48-server.txt)

Everytime I join a server it says this message 
![image](https://user-images.githubusercontent.com/112813663/188317995-4419dece-5a5d-4f13-9961-07b3b5719355.png)

Is there any solution to this pls?

### How can the issue be reproduced?

Joining a world or server.

**Comment by finallion** [comment]
Reinstall the mod and delete the config.

**Comment by ramon5457** [comment]
Thank you that worked :)

**Comment by ramon5457** [comment]
Thank you that worked :)
