### ISSUE TITLE
[1.19.2]Unable to stop dedicated server.

### ISSUE THREAD

**Issue by DrSigma4164** [finallion/The-Graveyard-FORGE-#53]
### What's the issue you encountered?

Unable to stop dedicated server. When I command the server to stop, it starts this process and stops at "Unable to stop dedicated server.", which is shown in the screenshot below. Here are the logs, I don't know if it was intended that way, but to stop the server I need to turn it off forcibly.
![image](https://user-images.githubusercontent.com/93322905/206804658-ec62a53d-57a5-4b73-8b3a-c50d53d23bb9.png)

### How can the issue be reproduced?

1) start the dedicated server
2) command the server to turn off
3) the shutdown process will begin, but it will not complete.

### Logs

Latest: https://gist.github.com/1aa0b1ad0077653250f038126c965e72.git    Debug: https://gist.github.com/c1ebbef37db80378054ab10fb7130aac.git

### Additional information

Minecraft: 1.19.2
Forge: 43.1.65
Mod version: The_Graveyard_2.2_(FORGE)_for_1.19.2.jar

**Comment by finallion** [comment]
I'm confused. The logs you send don't contain the error? 
When the server is stopping, my mod saves some data, thats the message. It doesn't affect the server stopping itself. But it seems like the server tries to stop multiple times, causing the mod to "save" the data multiple times. Can you provide the server logs or the logs where this screenshot is from?

**Comment by finallion** [comment]
I'm closing this for the moment due to missing information.
