### ISSUE TITLE
Server Spam "Readubg Graveyard Ghouling UUIDs in graveyardGhoulingUUIDMapping.txt."

### ISSUE THREAD

**Issue by SrRapero720** [finallion/The-Graveyard-FORGE-#54]
### What's the issue you encountered?

When a server start or stop, mod spam in console that message
![image](https://user-images.githubusercontent.com/29090346/211224028-7b758d6e-32fc-46a9-91ff-21c42bba9e21.png)

### How can the issue be reproduced?

- Start a DedicatedServer with the mod

### Logs

https://mclo.gs/Ssl2SJ6

### Additional information

Forge: 40.2.0
Mod: The_Graveyard_1.9.3_(FORGE)_for_1.18.2.jar || The_Graveyard_Biomes_1.1_(FORGE)_for_1.18.2.jar
Modpack: https://beta.curseforge.com/minecraft/modpacks/watermine-2

**Comment by finallion** [comment]
It only means that your server might be a bit slow when shutting down, causing this message to trigger more often. It doesn't affect any gameplay. And it should be "Reading" so thats an issue for sure I'm fixing.
