### ISSUE TITLE
[1.19.2] Dark Iron Blocks cannot be crafted into 9 Dark Iron Ingots

### ISSUE THREAD

**Issue by Kitteh6660** [finallion/The-Graveyard-FORGE-#56]
### What's the issue you encountered?

When I tried to put the Dark Iron Block into crafting grid, I expected that there would be 9 dark iron ingots. However, it shows nothing.

![image](https://user-images.githubusercontent.com/5838739/214371987-7c81741e-731e-4bfe-912e-3bb05106f35e.png)

### How can the issue be reproduced?

Step 1: Acquire Dark Iron Blocks.
Step 2: Try to uncraft them into ingots.
Step 3: Observe that you can't.

### Additional information

Versions used:

**Minecraft version:** 1.19.2
**Forge version:** 43.2.3
**Mod version:** 2.2

**Comment by finallion** [comment]
Added recipe in the newest version
