### ISSUE TITLE
[1.18.2] Sarcophagus are unoptimized as block entities

### ISSUE THREAD

**Issue by Reshy** [finallion/The-Graveyard-FORGE-#57]
### What's the issue you encountered?

I noticed in every world I loaded up that any time Sarcophagus were always top of the block entity tick list.  I'm not sure what causes it but it may be worth looking into a way to optimize the block entity.  The Braziers have a similar problem as well.

### How can the issue be reproduced?

Use the F3+Shift pie chart and go to block entities.

**Comment by finallion** [comment]
I changed the model in the newest version to reduce rendering power (as it is still the highest contributer to the lag caused by the block). The tick logic is mostly identical to the chest block entity. Hope this helps!
