### ISSUE TITLE
Allow Lich Summon Event to Occur in a Dimension with fixed_time

### ISSUE THREAD

**Issue by Darkosto** [finallion/The-Graveyard-FORGE-#58]
### Overview

Hello!

I've been using the Graveyard in a new project and so far it's been a lot of fun. I have custom worldgen and my Overworld dimension is set to a `fixed_time` which does not allow for the Lich summon to work. Is there a possibility you'd be able to add a config option or allow for the summon to happen even with a fixed time? I'm currently set to a time that is at night so the `isNight` check should technically still be working? Any thoughts?

```json
{
  "ultrawarm": false,
  "natural": true,
  "piglin_safe": false,
  "respawn_anchor_works": false,
  "bed_works": true,
  "has_raids": true,
  "has_skylight": false,
  "has_ceiling": true,
  "coordinate_scale": 1,
  "ambient_light": 0,
  "fixed_time": 15000,
  "logical_height": 688,
  "effects": "minecraft:the_nether",
  "infiniburn": "#minecraft:infiniburn_overworld",
  "min_y": -64,
  "height": 752
}
```

Thanks for your help and take care!
Darkosto

Graveyard: 1.9.3
Minecraft: 1.18.2
Forge: 40.2.0

### Why would this feature be useful?

This would be a useful addition to the mod that allows a bit more configuration for pack devs and should, hopefully, not break the mod's intent.

**Comment by finallion** [comment]
Hey, interesting! Just to be sure, all requirements are met when summoning the lich? So full bottle of blood, all three bone staff fragments at the right distance and not in peaceful?

**Comment by Darkosto** [comment]
Yup! That's correct, I confirmed that the setup was in the proper places and distances. After setting the blocks/items up the blood vial would not start the ritual so I saved and quit then disabled `fixed_time` went back into that same world and then blood vial worked right away.

**Comment by finallion** [comment]
Ok, I'm not really familiar with dimensions. Fixed time means there is not day and night cycle? Like the gamerule doDayNightCycle?
The check for the summoning is plainly world.isNight() so I'm not really sure why it is preventing the summoning.
And just for the sake of my sanity, the vial of blood in your offhand?

**Comment by Darkosto** [comment]
The fixed time should be visual only as it locks the sun/moon and brightness of that specific time, this is not the same as the gamerule so it shouldn't act the same. The blood vial did not work using fixed time in both off hand or main hand. Only the change of removing fixed time affected the ritual.

**Comment by finallion** [comment]
I will try some things and see how they go. 
Can you provide the dimension to playtest by any chance? Or a dimension mod, which uses the same settings? It would make testing a whole lot easier. And I'd keep everything confidential of course!

**Comment by Darkosto** [comment]
Okay! I've setup a small datapack for you to test with that only adds a fixed time to the dimension type of the overworld. The method I've used to test the ritual out is:
1. Create a new world with the datapck (fixed time is currently on and set to 15000
2. Place down ritual staff items and give myself a full vial of blood
3. Try clicking it onto the ritual block after the staff pieces have been placed
4. The ritual will not start
5. Close the world
6. Find the datapack saved in the Saves folder and remove the `fixed_time` line in the dimension type file
7. Restart the world and set the time to night
8.  Try the vial of blood again (it should start immediately)
[graveyard_test_datapack.zip](https://github.com/finallion/The-Graveyard-FORGE-/files/10961990/graveyard_test_datapack.zip)

Let me know what other questions I can answer to help out, thanks again!

**Comment by finallion** [comment]
Thank you, I found the issue.

public boolean isNight() {
      return !this.dimensionType().hasFixedTime() && !this.isDay();
   }

This is the method minecraft uses. So the isNight() check for the lich summoning fails. I updated the version, and it should work now!

**Comment by Darkosto** [comment]
Thank you very much for all of your help!
