### ISSUE TITLE
1.19.2   Command blocks structure generates near spawn

### ISSUE THREAD

**Issue by Herobattler** [finallion/The-Graveyard-FORGE-#59]
1.19.2   Command blocks structure generates near spawn

**Comment by finallion** [comment]
What? Can you elaborate a bit further?

**Comment by Herobattler** [comment]
There are a few command blocks with structure and entity spawn commands, who appear after loading into a new world.
This only ever happend after I downlaoded the latest 1.19.2 version of the Graveyard mod.

**Comment by finallion** [comment]
The mod doesn't use any command blocks. What make you think its from this mod? What kind of structure is this?

**Comment by Herobattler** [comment]
It happened right after i updated to the latest version of this mod, however it only happened once and was unable to reproduce it

**Comment by finallion** [comment]
It might be a coincidence and still be from another mod. As mentioned I never touched command blocks, and never made use of any other coding block in structures. If it happens again, feel free to take a screenshot and I can confirm if this structures is from the graveyard.
