### ISSUE TITLE
Graveyard biome overrides the Blindness effect

### ISSUE THREAD

**Issue by Reshy** [finallion/The-Graveyard-FORGE-#6]
![2021-11-27_22 59 37](https://user-images.githubusercontent.com/2096384/143732897-d5543cd3-3b62-4573-8ffe-9f2bf8161b47.png)
![2021-11-27_22 59 40](https://user-images.githubusercontent.com/2096384/143732889-e48b2230-1bce-4cf0-9e32-15de42b3c780.png)
![2021-11-27_22 59 42](https://user-images.githubusercontent.com/2096384/143732900-a0d4ede2-f629-435a-9e9f-f5e0c58edede.png)

As you can see, while you're within the Graveyard's biome, the Darkness effect doesn't apply properly, while it gets dark it doesn't get very dark.

**Comment by finallion** [comment]
Should be fixed in the next update.
