### ISSUE TITLE
[1.18.2] Duplicate variables in config files

### ISSUE THREAD

**Issue by Salvard** [finallion/The-Graveyard-FORGE-#61]
### What's the issue you encountered?

Hello,

In the config file "graveyard-common-1.18.2.toml", the variable "maxGroupSizeGhoul" appears twice, once in the category "[The Graveyard - Mob Spawning Config".reaper].

Have a nice day

### How can the issue be reproduced?

N/A

**Comment by finallion** [comment]
Fixed in latest update
