### ISSUE TITLE
Lich Boss Fight Config Customizations and UX Inquiry 

### ISSUE THREAD

**Issue by Darkosto** [finallion/The-Graveyard-FORGE-#62]
### Overview

Hello!

Would you consider the possibility of allowing the Lich boss fight to be configured via configs to more appropriately fine-tune the fight to a particular modpack? Currently, with how the boss fight is tuned it makes it incredibly challenging even with a set of decent gear, potions, and other helpful items. I've tried out the boss fight in a variety of ways to get a better idea of what I can do to provide a challenging yet balanced event for players. Even with higher level enchants the damage against the boss seems low which draws out the total time of the first phase alone. I'm not looking to make the fight easy by any means. But I do think it may be a little too powerful in a number of modpack situations. 

It would be very useful to have some configuration to set health (for each phase), damage, possibly timing for how often the minions are spawned, or stats for the minions themselves? I'm also attempting to fit the structure into a fully underground worldgen, is there a possibility of a config for the teleportation?  I tried the fight out wearing Netherite Armor with Prot IV, had a Netherite Sword and a Bow which both had high level vanilla enchants. The first phase took more than 10 minutes to get the boss down to 75% health and I had gone through 4 Totems of Undying and a pretty large amount of Golden Apples. The pillars in the arena are definitely helpful and I tried using those as often as I could to avoid the ranged spell attacks. I think the biggest struggly I have is with all of the phase 1 mechanics happening in such rapid succession that it feels overwhelming. I had barely any time between 4-5 minions chasing me, skeletons falling down from the sky, or spell attacks from the Lich. 

The second phase I felt was a fun twist on the fight, but ultimately, I was overwhelmed with how many mechanics were happening at any one time. The darkness effect is cool but is quickly turned to be frustrating when being chased by minions and randomly teleported across the arena. I found myself unable to be aware of my surroundings due to all of these mechanics happening at once. I was unsuccessful by using audio as an indicator for location because the sounds during the bossfight are much louder than any of the skeleton or lich movement sounds. I found myself being overly cautious and recognized the player is meant to have a sense of confusion during this phase (which is definitely a good mechanic) but really unable to overcome it outside of pure luck. More often than not, I would run directly into the boss and get killed in one or two hits and then have to make my way back to the boss arena. I also recognize the lich is meant to be extremely powerful in this phase, but I think the overall experience is muddied by the overwhelming amount of mechanics happening at any one given time. 

The third phase feels fine. It's definitely a much easier experience in comparison to the first two phases. It almost feels like the speed and damage is reversed with phase 1 due to how weak the lich is. However, I did discover that the boss does not have knockback resistance and in this phase I was able to knock it off the platform in just a few hits and he fell down to the ocean below and his AI broke. I went back and tested this out in previous phases and the boss was still able to be knocked off the platform but teleported back after a few moments. Can this happen during the third phase also? Or maybe knockback resistance or just not allowing the boss to leave the arena.

Something I did find out after my boss attempts was the audio for many of the lich's events are in stereo which would remove any directionality or volume differences based on location. Specifically, I noticed this on the `phase_three_attack_1.ogg` and `phase_three_attack_2.ogg` files. This sound event can be heard extremely far away and is always sounding like it's surrounding the player due to how Minecraft processes audio. I think those could be swapped to mono for better UX? 

I really enjoy the bossfight experience, there aren't very many opportunities to have a immersive audio and visuals to go with a boss fight. I think a few tweaks could help the overall experience. For my own edification, what is your vision in terms of what gear you want the player to have for this fight? Is this something that can be done using vanilla gear only? Or are you expecting higher tier modded gear? 

Thanks again for all your hard work on this mod and I really appreciate you taking the time on my long description!
Darkosto

### Why would this feature be useful?

Ultimately, I think a lot of my overview goes in depth about the usefulness of my propositions but I think user experience is really a motivational factor for this feature request.

**Comment by finallion** [comment]
Hey! First of all: thank you so much for your detailed and helpful feedback. I really appreciate the work you did and it makes my life a lot easier. 
Based on your suggestion I made the following changes:
- Reduced the armor value from 18 to 14 and thoughness value from 14 to 12. This should make the damage more noticable.
- Added configuration for most values (health in each phase, dmg, toughness, cooldown, mob summoning, spell duration, teleportation coords, ...)
- Removed the summing of mobs during the second (hunting) phase, as I agree, that too many things happen at once
- Fixed the knockback resistance not being registered, especially in the third phase
- Changed .ogg files to mono
- Made the "lich is close"-sound cue during hunt trigger from a greater distance to the player (this should - combined with the mono-sound and the now gone mobs spawns - make the second phase intense and desorienting without it being overwhelming or chaotic)
- Added visual particle feedback for the player teleporation during the hunt
- Made the player teleportation safe (in regards to your second reported issue)

These changes will be ported to all forge and fabric versions and I'm working on updating as fast as possible!
Big thanks for your feedback!

**Comment by finallion** [comment]
Ah and for my intentions: the idea was to make the lich achievable with vanilla armor. This was - in most cases - quite possible. But I see your point, that this might not be case for the majority of players. I tried to design a boss fight that IS a challenge for the player and can't be cheated (like the warden). Comments like yours help me a lot in balancing this fight to fit into vanilla and modded minecraft and to appeal to larger player base!

**Comment by Darkosto** [comment]
I really appreciate you taking this extremely well! I'll keep you posted and look forward to trying out the new changes! 😃
