### ISSUE TITLE
Lich Boss Teleport Event Does Not Always Teleport to a Safe Location

### ISSUE THREAD

**Issue by Darkosto** [finallion/The-Graveyard-FORGE-#63]
### What's the issue you encountered?

https://github.com/finallion/The-Graveyard-FORGE-/blob/5795a4a3d8d1c764a0ff1176ca1f2b30fabc3836/src/main/java/com/finallion/graveyard/entities/LichEntity.java#L422

During the boss fight phase where the player is teleported below the arena, the teleport event will look for a safe location but not use those coordinates when actually teleporting the player. Due to this issue, the player will sometimes be teleported into a wall and suffocate.

### How can the issue be reproduced?

An easy way to reproduce this is by not having an open area below the fight and you will be teleported into a wall. This happens less frequently when on the boss platform due to the amount of open space available.

**Comment by finallion** [comment]
Thanks :), fix will be added in the next update for all versions!

**Comment by finallion** [comment]
Fixed!
