### ISSUE TITLE
the game crashed when creating the world

### ISSUE THREAD

**Issue by masterstar2** [finallion/The-Graveyard-FORGE-#64]
### What's the issue you encountered?

[crash-2023-03-25_10.17.57-server](https://github.com/finallion/The-Graveyard-FORGE-/files/11068595/crash-2023-03-25_10.17.57-server.txt)

### How can the issue be reproduced?

unknown

**Comment by masterstar2** [comment]
its 1.18.2

**Comment by finallion** [comment]
Try to delete the config file and restart your game!

**Comment by masterstar2** [comment]
[crash-2023-03-26_06.55.13-client.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/11070472/crash-2023-03-26_06.55.13-client.txt)

**Comment by masterstar2** [comment]
> [crash-2023-03-26_06.55.13-client.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/11070472/crash-2023-03-26_06.55.13-client.txt) thats when i delete the config

**Comment by finallion** [comment]
Both of these crashlogs have nothing to do with the Graveyard. It says MutantMore is causing issues with its log file.

**Comment by masterstar2** [comment]
[crash-2023-03-26_13.36.35-server.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/11083632/crash-2023-03-26_13.36.35-server.txt)

**Comment by finallion** [comment]
Still nothing with the graveyard mod.
