### ISSUE TITLE
1.19.4 Support?

### ISSUE THREAD

**Issue by Aetrnl94** [finallion/The-Graveyard-FORGE-#66]
### Overview

Hi, this mod looks really cool! Is there any chance you can let us know if an update for 1.19.4 is going to be released, and if so, when we might be able to expect it? Thanks a lot and I can't wait to try it out!

**Comment by finallion** [comment]
Hey, an update for 1.19.4 is not planned as 1.20 will shortly release and most players are still using 1.19.2, I'm sorry!
