### ISSUE TITLE
Graveyard resetting config files

### ISSUE THREAD

**Issue by Reshy** [finallion/The-Graveyard-FORGE-#7]
![resetting](https://user-images.githubusercontent.com/2096384/143733229-cee71fb4-7bc8-4fbb-a954-a4b3baa6e08f.PNG)
![resetting2](https://user-images.githubusercontent.com/2096384/143733232-e571d93a-54f3-4085-b2c5-a353b2a600f0.PNG)

**Comment by finallion** [comment]
Reworked the config file. The next update will fix it.
