### ISSUE TITLE
Add a rotation to the item textures

### ISSUE THREAD

**Issue by SiverDX** [finallion/The-Graveyard-FORGE-#70]
### Overview

Hey,

if you add a rotation to the `gui` part of the `models\block\*.json` the item will look 3D

Example:
![image](https://github.com/finallion/The-Graveyard-FORGE-/assets/22003703/51c1ead5-2536-420d-a998-4ccef8e425fb)

Value used:
``` json
"gui": {
	"rotation": [30, 135, 0],
	"scale": [0.75, 0.75, 0.75]
},
```

Coffin Example:
![image](https://github.com/finallion/The-Graveyard-FORGE-/assets/22003703/d7c02b91-9ad5-4ab7-b881-167101bfffb3)

Values used:
``` json
"gui": {
	"rotation": [30, 135, 0],
	"translation": [-2, 0, 0],
	"scale": [0.35, 0.35, 0.35]
},
```

### Why would this feature be useful?

It looks better (in my opinion)

**Comment by SiverDX** [comment]
I did it for `gravestones`, `urns`, `small urns` and `coffins` with some slightly changed values if you're interested
![image](https://github.com/finallion/The-Graveyard-FORGE-/assets/22003703/5dc90593-5941-4f6f-954d-82eb12896ea6)

https://www.mediafire.com/file/giw1xi85p13t9uw/graveyard.zip/file

**Comment by finallion** [comment]
This is really great. I'm sorry for my late response, but I have integrated it for the next versions. It looks fantastic! Thank you very much :)
