### ISSUE TITLE
Why do you not make the GravestoneBlockEntity extend SignBlockEntity?

### ISSUE THREAD

**Issue by JustRed23** [finallion/The-Graveyard-FORGE-#73]
### Overview

Wouldn't this be easier? As the gravestone block is essentially just a redecorated sign.

**Comment by finallion** [comment]
Absolutely. But when I started modding I didn't know what I was doing. Would I do it different now? For sure. Do I bother with changing it or rather spend an hour in agony updating a logic that was meant for a sign and not for a gravestone? The second one!
