### ISSUE TITLE
mod crashes on 1.20

### ISSUE THREAD

**Issue by Devilswarchild** [finallion/The-Graveyard-FORGE-#74]
### What's the issue you encountered?

the base 1.20 mc version of your mod is set to require forge 47.0.3 when 1.20 is only at 46.0.14. 120.1 is at 47.03

can we please get a fix

![Screenshot_5](https://github.com/finallion/The-Graveyard-FORGE-/assets/27385258/16d570d6-bd60-4441-9141-a443b3fbf6fd)

### How can the issue be reproduced?

just launch graveyard mod in the base 1.20 version of modded mc on forge

### Additional information

logs for review:

[debug.log](https://github.com/finallion/The-Graveyard-FORGE-/files/11779816/debug.log)

[latest.log](https://github.com/finallion/The-Graveyard-FORGE-/files/11779817/latest.log)

[crash-2023-06-17_14.17.15-fml.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/11779818/crash-2023-06-17_14.17.15-fml.txt)

[launcher_log.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/11779819/launcher_log.txt)

**Comment by finallion** [comment]
Hm, I rather tend to exclude 1.20 due to potential issues on Mojangs side. Out of curiosity, why would you stay on 1.20?

**Comment by Devilswarchild** [comment]
because 1.20 hasnt even been out a whole month yet

**Comment by Devilswarchild** [comment]
and bc of the cornerstones for my modpack

**Comment by Devilswarchild** [comment]
those cornerstones being essentials, create, and minecolonies

**Comment by finallion** [comment]
ok.. give me a second

**Comment by finallion** [comment]
I uploaded a 1.20 version on CF. It will be approved in a few minutes

**Comment by Devilswarchild** [comment]
thank you. its now working as intended.
