### ISSUE TITLE
1.19.2 

### ISSUE THREAD

**Issue by BlackAures1** [finallion/The-Graveyard-FORGE-#75]
### What's the issue you encountered?

![image](https://github.com/finallion/The-Graveyard-FORGE-/assets/43911230/4a26b4e5-88c7-4818-b4c5-f22fcb0f6794)
you forgot to write the rules for the silk touch. Because of this error, the block does not drop when you try to gather it with silk.

### How can the issue be reproduced?

silk  touch

### Additional information

Correct
![image](https://github.com/finallion/The-Graveyard-FORGE-/assets/43911230/30b0b9c0-bbe7-467f-be5a-1264224a3437)
 
 or
```
  "type": "minecraft:block",
  "pools": [
    {
      "bonus_rolls": 0.0,
      "entries": [
        {
          "type": "minecraft:alternatives",
          "children": [
            {
              "type": "minecraft:item",
              "conditions": [
                {
                  "condition": "minecraft:match_tool",
                  "predicate": {
                    "enchantments": [
                      {
                        "enchantment": "minecraft:silk_touch",
                        "levels": {
                          "min": 1
                        }
                      }
                    ]
                  }
                }
              ],
              "name": "WRITE_HERE_YOUR_BLOCK"
            },
```

**Comment by BlackAures1** [comment]
It cannot be extracted with any tool other than the bare hand

**Comment by finallion** [comment]
No, this is not intended. Thanks for letting me know! I'll fix it for the next update
