### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by I2pRandom** [finallion/The-Graveyard-FORGE-#76]
### What's the issue you encountered?

Crashes loading the game.

[crash-2023-06-26_11.36.16-client.txt](https://github.com/finallion/The-Graveyard-FORGE-/files/11871597/crash-2023-06-26_11.36.16-client.txt)

### How can the issue be reproduced?

Error is consistent.

**Comment by finallion** [comment]
The file is in the assets. If it is not found, the downloaded version is probably corrupted or outdated. I suggest redownloading the mod!

**Comment by I2pRandom** [comment]
After redownloading 3 times, i've identified that the asset is indeed in the Jar with WinRar. Forge is failing to see it for an unknown reason. 
Probably an incompatibility
