### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by azzurasignis** [finallion/The-Graveyard-FORGE-#79]
### What's the issue you encountered?

[19:40:30] [Worker-Main-5/ERROR] [minecraft/HangingEntity]: Hanging entity at invalid position: BlockPos{x=2, y=-56, z=-41}

I have this error message and it causes problems (crash and lag) I am in a server on forge !

### How can the issue be reproduced?

idk

### Logs

[Worker-Main-5/ERROR] [minecraft/HangingEntity]: Hanging entity at invalid position: BlockPos{x=2, y=-56, z=-41}

**Comment by finallion** [comment]
Its a server log from an item frame generated with a structure. It doesn't cause lag or crashes, it is a simple log message that logs when the item frame is loaded. I don't know why mojang felt the need to log this, but it is harmless

**Comment by azzurasignis** [comment]
ok thanks ^^
