### ISSUE TITLE
1.19.2 Server Bug (Items not showing)

### ISSUE THREAD

**Issue by Kixxerin** [finallion/The-Graveyard-FORGE-#80]
After adding the mod to a singleplayer modpack it worked perfectly, with no issues whatsoever, however when I added the mod to a server modpack, I see the tab for graveyard in the creative menu, however the tab is empty and I am unable to access The Graveyard modded items from both the creative menu and the console.

Upon checking both the Debug console and latest.log no mention of The Graveyard was found, and the list of loaded mods does not include the Graveyard.

Info:
Mod Version: The_Graveyard_2.5.3_(FORGE)_for_1.19.2..jar
Forge Loader: Forge 43.2.21
Minecraft version: 1.19.2
Server Host: Bisect Hosting

**Comment by Kixxerin** [comment]
debug.log and latest.log
[debug.log](https://github.com/finallion/The-Graveyard-FORGE-/files/12210976/debug.log)
[latest.log](https://github.com/finallion/The-Graveyard-FORGE-/files/12210977/latest.log)

**Comment by finallion** [comment]
The mod is both on client and server?
DId you try it with a downgraded version of forge, like 43.2.0?

**Comment by finallion** [comment]
Closing this due to missing information.
