### ISSUE TITLE
1.19.2 Revenent & Ghoul Unable To Spawn

### ISSUE THREAD

**Issue by LifelessAmir** [finallion/The-Graveyard-FORGE-#82]
There is an issue with versions 2.5 to 2.5.3 (the newest version of the graveyard forge for 1.19.2) that no matter how high the weight value of the mobs Revenent and Ghoul are, they just do not spawn naturally in low light levels unless there is a horde and the mobs Nightmare and Skeleton Creeper are really really rare to find too. I had to backport my mod to version 2.2 in 1.19.2 forge for them to finally spawn in. There is also no other mods colliding with it so thats out of the question. I hope you guys can fix the problem because now I don't have Nameless Hanged and the boss music in my version (2.2). Have a great day ya'll!

**Comment by finallion** [comment]
Sorry, I can't confirm it in my tests, spawning works as intended. The spawns of ghouls and revenants are biome dependent, ghouls only spawn in swamps and coniferous forests, revenants only in cold biomes. Did you test those?
