### ISSUE TITLE
Where to find Staffs

### ISSUE THREAD

**Issue by XavierBit** [finallion/The-Graveyard-FORGE-#83]
### Overview

Hi!
We are playing on Minecraft 1.20.1 with the Fabric version of Graveyard and are enjoying every second!

After defeating the Lich I saw that there are more and different staffs to find
![image](https://github.com/finallion/The-Graveyard-FORGE/assets/95314871/9caba5ac-9e62-4a9c-aa7d-0f80d9a27b00)

I searched high and low to find any explanation on how to obtain those, but my search came up with nothing!

Could you explain or send me a link with more information about those staffs?

Thanks for many hours of exciting game play... we really do love this mod!

**Comment by finallion** [comment]
Hey :) happy to hear and thank you for the kind words. For now, the Corrupted Champion has a chance of dropping all different staff variations. I plan on making them more unique drops!

**Comment by XavierBit** [comment]
Thanks for the answer finallion!

We'll keep slaying then ;)
