### ISSUE TITLE
The graveyards are not spawning

### ISSUE THREAD

**Issue by gsmdsintetsu** [finallion/The-Graveyard-FORGE-#84]
Well..I many mods in my Minecraft, including "The Graveyard mod", but when I changed the old file from the new file with a new version one I can't find any of it in my minecraft world. The version I'm talking is "The Graveyard 2.5.3 (FORGE) for 1.19.2" and the old file is "The Graveyard 2.2 (FORGE) for 1.19.2".

POV: It still happens even if I start a new world

**Comment by finallion** [comment]
I'd need the logs. Did you try to run the locate command?
