### ISSUE TITLE
1.19.2 Forge Ceramics drops not working

### ISSUE THREAD

**Issue by Phistandantilus** [finallion/The-Graveyard-FORGE-#85]
testing a modpack in single player, loaded several worlds with The Graveyard and a hefty amount of other mods, haven't gotten ceramics to drop anything since the start in Forge 1.19.2. 

thinking it might be a mod compatibility issue, I tried deactivating all the other mods through Curseforge, repairing the installation, and loading a new game with only The Graveyard and Geckolib active. the results were the same, however, and there were no random drops from ceramics.

I'd certainly like to have those drops in Forge like in the Fabric version, if its possible, since most of the content I want for my modpack is forge exclusive.

**Comment by finallion** [comment]
Over the past weeks I tested several versions and couldn't reproduce the bug at all. In creative mode the ceramics never drop anything - only in survival.
