### ISSUE TITLE
Make Corrupted vindicators and pillagers render their hand items and armor correctly

### ISSUE THREAD

**Issue by betterworld-sjq** [finallion/The-Graveyard-FORGE-#87]
### Overview

Make Corrupted vindicators and pillagers correctly show their weapons and armor.

### Why would this feature be useful?

Some mods may make all kinds of mobs randomly wear armor and hold weapons. And these two human-like mobs may seem a pity if can't be rendered well.

**Comment by finallion** [comment]
Added in 3.2
