### ISSUE TITLE
1.19.2 How to prevent Acolytes from spawning in crypt?

### ISSUE THREAD

**Issue by KIaxons** [finallion/The-Graveyard-FORGE-#88]
### Overview

So, we've found a crypt, scout it and decide to establish our Nether Studying Laboratory there, even start massive elevator construction to may ably be reach catacombs faster from the surface. But then a problem occurred - Acolytes.

We searched crypts several times, wiped all spawners around, but yet, these violet dudes continues to spawning around in litteraly bare air under ceiling. We started to remove walls to find some possible hidden spawners - removed all amethyst blocks and sarcophagus around, but yet - spawns want stop even a little.

So my question is - how to prevent acolytes from spawning FOR GOOD? And to be polite I must say, that firstly we searched around Internet with no result. Posting my question here is straight act of despair D:

**Comment by finallion** [comment]
src/main/resources/data/graveyard/worldgen/structure/crypt.json

There is an entry for acolytes. Removing this will stop them from spawning

**Comment by KIaxons** [comment]
Oh, thanks, then :{  I just thought it could be blocked by any ingame methods.
