### ISSUE TITLE
"Incarnated Evil" Abruptly Stopping While Playing

### ISSUE THREAD

**Issue by Hallownest** [finallion/The-Graveyard-FORGE-#89]
### What's the issue you encountered?

It is worth noting this is on Graveyard 2.6.2, Forge, Version 1.20.1. I could not find an area for this version, and assumed this was for bugs 1.18.1 or above. If I posted this in the wrong place, I apologize and can move it.

I was ecstatic to have found this music disc, as I really love the song and enjoy collecting discs. However. within a few seconds of playing, the song just... stops. Like, with no warning or anything. I have tried playing the disc several times after to make sure I wasn't missing anything. Surely the song isn't meant to just stop? It is worth noting, I am using other mods, but have no idea why any other mod would make a music disc abruptly stop. Every other vanilla and non vanilla music disc I've encountered so far has worked fine.

### How can the issue be reproduced?

Simply by playing the disc. I tried uploading a file to show this, but the file size was too big to put here. Regardless, it's not a very complex issue.

**Comment by finallion** [comment]
Can this error be reproduced in 3.0/3.1 for 1.20.1?
