### ISSUE TITLE
Creeper glowing eyes texture is messing with my texturepack

### ISSUE THREAD

**Issue by Frog1en** [finallion/The-Graveyard-FORGE-#90]
### Overview

Hello! looks like creeper glowing eyes texture is messing with my texturepack but i would love to keep both in my modpack! maybe  u could tell me how can i fix this or delete glowing eyes texture? Thanks in advance!
![2023-11-08_08 24 04](https://github.com/finallion/The-Graveyard-FORGE/assets/149720855/40fb17b0-c485-4667-87f5-2ef458176d3d)

**Comment by finallion** [comment]
The glowing eyes are a render layer above the actual texture. I believe it is similar to the enderman eyes. I'm afraid I can't help you fixing your texturepack to work along side the mod, as I dont know much about texturepacks. 
Deleting is not possible without modifying the code.
