### ISSUE TITLE
1.20.1 Forge 47.2.0

### ISSUE THREAD

**Issue by Crafty1340** [finallion/The-Graveyard-FORGE-#92]
### What's the issue you encountered?

The game crashes when loading with EMF (Entity Model Features) 1.1.0 for 1.20.1.

### How can the issue be reproduced?

1. Download 1.20.1 Forge.
2. Download EMF 1.20.1-1.1.0.
3. Launch the game.

### Logs

Not sure what they are.

### Additional information

Nothing really.

**Comment by finallion** [comment]
Doesn't look like an issue on my side I'm afraid
