### ISSUE TITLE
Hanged man's customization deals 1.19.2

### ISSUE THREAD

**Issue by BlackAures1** [finallion/The-Graveyard-FORGE-#96]
### Overview

Give any opportunity for developers to customize the nameless hanged man. Datapack, config, or anything else. For vanilla villagers, I use [custom-villager-trades](https://www.curseforge.com/minecraft/mc-mods/custom-villager-trades-forge) 

### Why would this feature be useful?

I checked the mod data and the configs. It seems that this function does not exist in the mod. It is important for me that all transactions are customizable in my modpack. I don't want to just disable this mob. It's creepy and charismatic.

**Comment by finallion** [comment]
This is a feature in 1.20.1 but I do not plan on backporting it to 1.19, sorry!

**Comment by BlackAures1** [comment]
okie, thanks for answer
