### ISSUE TITLE
1.19.2 Texture loss when interacting with the mod.  

### ISSUE THREAD

**Issue by Krimatoria** [finallion/The-Graveyard-FORGE-#97]
### What's the issue you encountered?

Forge 43.3.7
Carryon-forge-1.19.2-2.1.1.22.jar
The_Graveyard_2.5.3_(FORGE)_for_1.19.2..jar

Taking the coffin with the CarryOn mod, the texture disappears during installation.

![2024-01-23_17 22 36](https://github.com/finallion/The-Graveyard-FORGE/assets/106809386/665870fb-fc9d-45c6-bd89-0a25ce50d067)
![2024-01-23_17 27 31](https://github.com/finallion/The-Graveyard-FORGE/assets/106809386/989f9186-a04e-4397-9ce0-a5c32a9a8cfb)
![2024-01-23_17 22 53](https://github.com/finallion/The-Graveyard-FORGE/assets/106809386/0d759eb2-ac71-4d2d-943c-f0f2a929aa2a)

### How can the issue be reproduced?

Just install the mods, pick up the coffin and try it. The texture disappears after installing the item, but it will be at the moment of taking. 

If you just hold down the left mouse button to take down the object and install it again, the texture will return. I.e. this is a problem of purely mod interaction.

### Additional information

I don't see any errors related to mods in the logs.

**Comment by finallion** [comment]
Sounds like a problem on the side of CarryOn? Not quite sure what I'm supposed to do here

**Comment by Krimatoria** [comment]
> Похоже на проблему на стороне CarryOn? Не совсем понимаю, что мне здесь делать

Well, yes) they just don't answer yet
