### ISSUE TITLE
Command /Summon Missing Texture (1.20.1)

### ISSUE THREAD

**Issue by Blaze442-1** [finallion/The-Graveyard-FORGE-#98]
### What's the issue you encountered?

Hello hope you are having a great day, I had a problem in my server whenever I use a /summon command with certain mobs such as the Ghoul, and the Ghouling which both have missing textures when summoned, I was working on a project to implement these mobs in my server and be part of a story of sorts and its generally a lore based server, so the missing texture felt incomplete, just a heads up for future updates if you can just implement that fix in would be greatly appreciated! : )

### How can the issue be reproduced?

Generally what I did was /summon a ghoul or ghouling got its nbt and put it into a command, spawn egg, or spawner, but everytime it spawns i noticed that even the basic /summon command, if it does not have the animation from those 2 monsters coming out of the ground, it affects and has a missing texture, or to add onto that it sometimes also if killed before rising up to the surface fully it will appear as if it is in an idle and frozen state for less then a second(this is just an extra measure and is not necessarily as visually disruptive).

once more you can look into detail yourself if your interested thank you for your assistance and patience! : D

### Logs

N/A

### Additional information

N/A

**Comment by finallion** [comment]
Hey! Thanks for reaching out. The texture is applied as data value onto the entity.
I'm not quite familiar with the summon command and the use of NBT-data inside that command, but
"/data modify entity 003252ce-6c8c-4f18-b028-2d4ddef11ef8 ghoulVariant set value 2" for example works to set the value. Maybe something similar is achievable with the summon command?

Regarding the "frozen" animation: I'm afraid there is not much I can do. On spawn it plays the "spawn"-animation, and if killed while this animation is played, it happens that the "dead"-animation does not trigger as the previous is still running. But I'll try to maybe find a workaround!
