### ISSUE TITLE
Nightmare Fix 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [finallion/The-Graveyard-FORGE-#99]
### What's the issue you encountered?

**Does this entity have to do something? She just stands and walks and that's it)**
![image](https://github.com/finallion/The-Graveyard-FORGE/assets/106809386/c2900c2e-b00e-4ca7-9422-7b493b1d3a1a)

### How can the issue be reproduced?

I have a Fear Nightfall build 11.5

### Logs
No problem detected
_No response_

### Additional information
The_Graveyard_2.5.3_(FORGE)_for_1.19.2..jar
_No response_

**Comment by finallion** [comment]
It only attacks when directly looking at its head (your cursor needs to be rougly centered)

**Comment by Krimatoria** [comment]
> Он атакует только тогда, когда смотрит прямо на его голову (курсор должен быть примерно по центру)

I'll try it today, I just haven't seen him attack once.

**Comment by Krimatoria** [comment]
@finallion I had another mistake related to your mod and "CarryON", I hope it will also be considered [later](https://github.com/finallion/The-Graveyard-FORGE/issues/97).

**Comment by Krimatoria** [comment]
> It only attacks when directly looking at its head (your cursor needs to be rougly centered)

No, I look at him and nothing happens.

**Comment by Krimatoria** [comment]
> It only attacks when directly looking at its head (your cursor needs to be rougly centered)

Is there any way to fix this?

**Comment by finallion** [comment]
Not being able to reproduce. Attacks normal

**Comment by AikaBack** [comment]
> > It only attacks when directly looking at its head (your cursor needs to be rougly centered)
> 
> Is there any way to fix this?

maybe you have mods that alter mobs AI? maybe Enhanced AI? For example cave dweller mod needs its mob to be added to blacklist for mob to work properly alongside Enhanced AI.

**Comment by Krimatoria** [comment]
> > > Он атакует только тогда, когда смотрит прямо на его голову (курсор должен быть примерно по центру)
> > 
> > 
> > Есть ли способ это исправить?
> 
> может у вас есть моды изменяющие ИИ мобов? может быть, улучшенный ИИ? Например, моду пещерного жителя необходимо добавить своего моба в черный список, чтобы моб правильно работал вместе с Enhanced AI.

Yes) but I do not know how to set up a blacklist for mobs from Enhanced AI?

**Comment by AikaBack** [comment]
you need to make datapack with this exact structure "datapackname\data\enhancedai\tags\entity_types" and in this folder you need to add 2 files in which you need to add mob's correct name that is displayed if you look at it with f3 menu at the right.
[no_follow_range_changes.json](https://github.com/finallion/The-Graveyard-FORGE/files/14318738/no_follow_range_changes.json)
[no_target_changes.json](https://github.com/finallion/The-Graveyard-FORGE/files/14318739/no_target_changes.json)
You need to follow guide how to make datapack for your version of minecraft.

**Comment by Krimatoria** [comment]
> enhancedai

If the creator of the mod had added a Blacklist, it would not have taken such a long way) Blacklist is in very large mods and it is strange that it is not here. I looked at the datapack, I don't know much English and I write everything through a translator and I don't understand programming. I hope he will just add this Blacklist to his mod someday) But thank you)

**Comment by AikaBack** [comment]
I gave you instruction how to do that though datapack, there is no programming envolved. Its easy.

**Comment by Krimatoria** [comment]
> I gave you instruction how to do that though datapack, there is no programming envolved. Its easy.

Its ok?
[Nightmare.zip](https://github.com/finallion/The-Graveyard-FORGE/files/14381057/Nightmare.zip)
